services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - app-network
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  
networks:
  app-network: