services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
  
networks:
  app-network: